/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registroempleados;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author esthe
 */
public class frmResgristoEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form frmResgristoEmpleados
     */
    public frmResgristoEmpleados() {
        initComponents();
        this.TablaEmpleados.setModel(model);
        this.model.addColumn("Codigo");
        this.model.addColumn("Empeado");
        this.model.addColumn("Cardo");
        this.model.addColumn("Fecha de contrato");
        this.model.addColumn("Sueldo Final");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        btoGrabar = new javax.swing.JButton();
        btoNuevo = new javax.swing.JButton();
        btoEliminar = new javax.swing.JButton();
        btoSalir = new javax.swing.JButton();
        comboCargo = new javax.swing.JComboBox<>();
        btoEditar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboTipoContratacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSueldoFinal = new javax.swing.JTextField();

        jButton3.setText("Editar(Actualizar)");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Regristro de empleados");

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpleados);

        jLabel2.setText("Codigo");

        jLabel3.setText("Empleado");

        jLabel4.setText("Cargo");

        jLabel5.setText("Fecha de contrato");

        jLabel6.setText("Sueldo ofrecido por hora");

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });

        btoGrabar.setText("Grabar");
        btoGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoGrabarActionPerformed(evt);
            }
        });

        btoNuevo.setText("Nuevo");
        btoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoNuevoActionPerformed(evt);
            }
        });

        btoEliminar.setText("Eliminar");
        btoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoEliminarActionPerformed(evt);
            }
        });

        btoSalir.setText("Salir");
        btoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalirActionPerformed(evt);
            }
        });

        comboCargo.setEditable(true);
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Doctor", "Ingeniero", "Abogado" }));
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });

        btoEditar.setText("Editar(Actualizar)");
        btoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoEditarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de contratacion");

        comboTipoContratacion.setEditable(true);
        comboTipoContratacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Parcial", "Tiempo completo" }));
        comboTipoContratacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoContratacionActionPerformed(evt);
            }
        });

        jLabel9.setText("Sueldo final");

        txtSueldoFinal.setEditable(false);
        txtSueldoFinal.setBackground(new java.awt.Color(204, 204, 255));
        txtSueldoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btoGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipoContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSueldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(btoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoGrabar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoNuevo))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btoEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btoEliminar)
                    .addComponent(jLabel5)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTipoContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSueldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel model=new DefaultTableModel();
    
    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btoGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoGrabarActionPerformed
        // TODO add your handling code here:
        this.model.addRow(new Object[]{this.txtCodigo.getText(),this.txtEmpleado.getText(),
            this.comboCargo.getSelectedItem(),this.txtFecha.getText(),this.txtSueldoFinal.getText()});
        this.txtCodigo.setText("");
        this.txtEmpleado.setText("");
        this.comboCargo.setSelectedIndex(0);
        this.txtFecha.setText("");
        this.comboTipoContratacion.setSelectedIndex(0);
        this.txtSueldoFinal.setText("");
        txtCodigo.grabFocus();     
    }//GEN-LAST:event_btoGrabarActionPerformed

    private void btoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoEliminarActionPerformed
        // TODO add your handling code here:
        int fila_seleccionada=TablaEmpleados.getSelectedRow();
        if(fila_seleccionada>=0){
            this.model.removeRow(fila_seleccionada);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila por favor");
          
        }  
    }//GEN-LAST:event_btoEliminarActionPerformed

    private void btoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoNuevoActionPerformed
        // TODO add your handling code here:
        this.txtCodigo.setEnabled(true);
        this.txtCodigo.setText("");
        this.txtEmpleado.setText("");
        this.comboCargo.setSelectedIndex(0);
        this.txtFecha.setText("");
        this.txtSueldo.setText("");
        this.txtSueldoFinal.setText("");
      this.comboTipoContratacion.setSelectedIndex(0);
        txtCodigo.grabFocus();
       
    }//GEN-LAST:event_btoNuevoActionPerformed
    int filas;
    private void btoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoEditarActionPerformed
        // TODO add your handling code here:
      String []datos=new String[5];
      datos[0]=txtCodigo.getText();
      datos[1]=txtEmpleado.getText();
      datos[2]=this.comboCargo.getSelectedItem().toString();
      datos[3]=txtFecha.getText();
      datos[4]=txtSueldo.getText();
      
      for(int i=0; i < TablaEmpleados.getColumnCount(); i++){
          this.model.setValueAt(datos[i], this.filas,i );
       
      }
      
    }//GEN-LAST:event_btoEditarActionPerformed

    private void TablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadosMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada=TablaEmpleados.getSelectedRow();
        txtCodigo.setText(TablaEmpleados.getValueAt(fila_seleccionada, 0).toString());
        txtEmpleado.setText(TablaEmpleados.getValueAt(fila_seleccionada, 1).toString());
        comboCargo.setSelectedItem(TablaEmpleados.getValueAt(fila_seleccionada, 2).toString());
        txtFecha.setText(TablaEmpleados.getValueAt(fila_seleccionada, 3).toString());
        txtSueldoFinal.setText(TablaEmpleados.getValueAt(fila_seleccionada, 4).toString());
        filas = fila_seleccionada;
    }//GEN-LAST:event_TablaEmpleadosMouseClicked

    private void btoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btoSalirActionPerformed

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        // TODO add your handling code here:
        System.out.println("evt"+evt.getActionCommand());
        System.out.println("valor de item "+this.comboCargo.getSelectedItem().toString());
        String cargoSeleccionado=this.comboCargo.getSelectedItem().toString();
        Double sueldoDefault;
        sueldoDefault = 0D;  
        switch (cargoSeleccionado) {
            case "Administrador":
                sueldoDefault = 100D;
                break;
            case "Doctor":
                sueldoDefault = 150D;
                break;
            case "Ingeniero":
                sueldoDefault = 200D;
                break;
            case "Abogado":
                sueldoDefault = 250D;
                break;
            default:
                sueldoDefault = 0D;

        }
        System.out.println("que es sueldo default" +sueldoDefault );
        this.txtSueldo.setText(sueldoDefault.toString());
        this.txtSueldoFinal.setText(sueldoDefault.toString());
    }//GEN-LAST:event_comboCargoActionPerformed

    private void txtSueldoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoFinalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSueldoFinalActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void comboTipoContratacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoContratacionActionPerformed
        // TODO add your handling code here:
        String tipoContratacion = this.comboTipoContratacion.getSelectedItem().toString();
        Double sueldoFinal = 0D;
        Double sueldoOfrecidoPorHora = 0D; //Double.parseDouble(this.txtSueldo.getText());
        boolean valuar = this.txtSueldo.getText().isEmpty();
        if (valuar) {
            sueldoOfrecidoPorHora = 0D;
        }else{
            sueldoOfrecidoPorHora = Double.parseDouble(this.txtSueldo.getText());
        }
       
        switch (tipoContratacion) {
            case "Parcial":
                sueldoFinal = sueldoOfrecidoPorHora * 4;
                break;
            case "Tiempo completo":
                sueldoFinal = sueldoOfrecidoPorHora * 8;
                break;
            default:
               sueldoFinal = 0D;

                
        
        }
        this.txtSueldoFinal.setText(sueldoFinal.toString());
        
        
        
    }//GEN-LAST:event_comboTipoContratacionActionPerformed
  
    DefaultTableModel modelo=new DefaultTableModel();
    /**;
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmResgristoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmResgristoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmResgristoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmResgristoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmResgristoEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JButton btoEditar;
    private javax.swing.JButton btoEliminar;
    private javax.swing.JButton btoGrabar;
    private javax.swing.JButton btoNuevo;
    private javax.swing.JButton btoSalir;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboTipoContratacion;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldoFinal;
    // End of variables declaration//GEN-END:variables

   
}
